config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'pages#home', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  get '/characters/edit', to: 'characters#edit', :as => :edit_char
  get '/petty_crime', to: 'pages#pretty_crime', :as =>:petty_crime

  resources :characters, only:[:show,:new,:create,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  GENDERS = ["1","2"]

  RANKS = {
    1 => "Soldier",
    2 => "Sergeant",
    3 => "General"
  }

  scope :online, -> { where(:online => true) }
  belongs_to :user
  mount_uploader :image, ImageUploader
  before_validation :have_active_character?, :on => :create
  validates :name, length: {minimum: 3, maximum: 16}
  validates :gender, inclusion: { in: GENDERS }
  validates_presence_of :name,:image,:gender,:user
  validates_uniqueness_of :name, :message => "This name is already being used"



  def rankname
    RANKS[self.rank]
  end

  def have_active_character?
    if !user.active_character.nil?
      errors.add(:base, "You already have an active character")
    end
  end

  def toggle_online
    self.toggle!(:online)
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :characters, dependent: :destroy
  has_one :active_character, -> { where(alive: true) }, class_name: 'Character', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path
    end
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @character = Character.all.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def edit
    @character = current_user.active_character
  end

  def create
    @character = current_user.characters.new(character_params)

    respond_to do |format|
      if @character.save
        format.html  { redirect_to(@character,
                      :notice => 'Character was successfully created. Good luck!') }
        format.json  { render :json => @character,
                      :status => :created, :location => @character }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @character.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def update
    @character = current_user.active_character

    respond_to do |format|
      if @character.update_attributes(character_params)
        format.html  { redirect_to(@character,
                      :notice => 'Character was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @character.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :gender,:image,:online)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!

  def home
    @user = current_user
  end

  def pretty_crime
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/edit.html.erb
<div class="col-sm-offset-3">
  <h2>Edit Character</h2><br>
</div>
<%= form_for @character, html: {class: "row form-horizontal"}, :action => 'update' do |f| %>
<% if @character.errors.any? %>
  <div id="errorExplanation">
    <% @character.errors.full_messages.each do |msg| %>
    <div class="row">
      <div class="alert alert-danger col-sm-6" role="alert"><strong><%= msg %>!</strong></div>
    </div>
    <% end %>

  </div>
<% end %>
  <fieldset disabled>
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-1 col-sm-offset-3 control-label'%>
      <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control disabled' %>
      </div>
    </div>
  </fieldset>

  <div class="form-group">
      <%= f.label :image, class: 'col-sm-1 col-sm-offset-3 control-label'%>
      <div class="col-sm-5">
        <%= f.file_field :image, class: 'form-control' %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :gender, class: 'col-sm-1 col-sm-offset-3 control-label' %>
    <div class="col-sm-2">
      <%= f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-offset-3 col-sm-6">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  </div>

  <% end %>

app/views/characters/edit.html.haml
%div
  %h2 Edit Character
  %br
=form_for @character, html: {class: "row form-horizontal"}, :action => 'update' do |f|
  -if @character.errors.any?
    .errorExplanation
      -@character.errors.full_messages.each do |msg|
        .row
          .alert.alert-danger.col-sm-6{role: "alert"}
            %strong= msg
  %fieldset.disabled
    .form-group
      = f.label :name, class: 'col-sm-1 col-sm-offset-3 control-label'
      .col-sm-5
        = f.text_field :name, class: 'form-control disabled'
    .form-group
      = f.label :image, class: 'col-sm-1 col-sm-offset-3 control-label'
      .col-sm-5
        = f.file_field :image, class: 'form-control'
    .form-group
      = f.label :gender, class: 'col-sm-1 col-sm-offset-3 control-label'
      .col-sm-2
        = f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"})
    .form-group
      .col-sm-offset-1.col-sm-offset-3.col-sm-6
        = f.submit "Submit", class: "btn btn-default"

app/views/characters/edits.html.erb
<div class="col-sm-offset-3">
  <h2>Edit Character</h2><br>
</div>
<%= form_for @character, html: {class: "row form-horizontal"}, :action => 'update' do |f| %>
<% if @character.errors.any? %>
  <div id="errorExplanation">
    <% @character.errors.full_messages.each do |msg| %>
    <div class="row">
      <div class="alert alert-danger col-sm-6" role="alert"><strong><%= msg %>!</strong></div>
    </div>
    <% end %>

  </div>
<% end %>
  <fieldset disabled>
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-1 col-sm-offset-3 control-label'%>
      <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control disabled' %>
      </div>
    </div>
  </fieldset>

  <div class="form-group">
      <%= f.label :image, class: 'col-sm-1 col-sm-offset-3 control-label'%>
      <div class="col-sm-5">
        <%= f.file_field :image, class: 'form-control' %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :gender, class: 'col-sm-1 col-sm-offset-3 control-label' %>
    <div class="col-sm-2">
      <%= f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-offset-3 col-sm-6">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  </div>

  <% end %>

app/views/characters/new.html.erb
  <%= form_for @character, html: {class: "form-horizontal"}, :action => 'create' do |f| %>
  <% if @character.errors.any? %>
    <div id="errorExplanation">
      <% @character.errors.full_messages.each do |msg| %>
      <div class="row">
        <div class="alert alert-danger col-sm-6" role="alert"><strong><%= msg %>!</strong></div>
      </div>
      <% end %>

    </div>
  <% end %>
    <% if @character.errors.include?(:name)  %>
    <div class="form-group has-error has-feedback">
      <%= f.label :name, class: 'col-sm-1 control-label'%>
      <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control', id: "inputWarning1"%>
        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
          <% @character.errors.full_messages_for(:name).each do |msg| %>
            <span id="helpBlock2" class="help-block"><%= msg %></span>
          <% end %>
      </div>
    </div>
    <% else %>
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-1 col-sm-offset-3 control-label'%>
        <div class="col-sm-5">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
    <% end %>



    <div class="form-group">
        <%= f.label :image, class: 'col-sm-1 col-sm-offset-3 control-label'%>
        <div class="col-sm-5">
          <%= f.file_field :image, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group">
      <%= f.label :gender, class: 'col-sm-1 col-sm-offset-3 control-label' %>
      <div class="col-sm-2">
        <%= f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"}) %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-offset-3 col-sm-6">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>

    <% end %>

app/views/characters/show.html.erb
<div class="row">
    <div class="col-xs-6 col-xs-offset-3 col-sm-8 col-sm-offset-2">
        <div class="well well-sm">
            <div class="row">
                <div class="col-sm-4">
                    <%= image_tag(@character.image.thumbnail.url) %>
                    <!-- <div class="btn-group">
                        <button type="button" class="btn btn-primary">
                            Action</button>
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span><span class="sr-only">Action</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Message</a></li>
                            <li><a href="#">Mug</a></li>
                            <li><a href="#">Kill</a></li>
                        </ul>
                    </div> -->
                </div>
                <div class="col-sm-6", style='text-align:left'>
                    <h2> <%= @character.name %></h2>
                    <h5><%= @character.rankname %></h5>
                    <p><small>
                      Posts: 0<br>
                      Messages: 0<br>
                      Last seen: <%=@character.user.last_sign_in_at.strftime("%d-%m-%Y, %H:%M") %><br>
                      Registered: <%=@character.created_at.strftime("%d-%m-%Y, %H:%M") %>
                    </small></p><br>
                    <!-- Split button -->
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TbGame</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='container' style="text-align:center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'shared/online' %>
    </div>

  </body>
</html>

app/views/pages/_new_char.html.haml
= form_for @char, html: {class: "form-horizontal"} do |f|
  -if @char.errors.any?
    #errorExplanation
      %h2
        = pluralize(@char.errors.count, "error")
          prohibited this char from being saved
      %ul
          -@char.errors.full_messages.each do |msg|
          %li
            = msg


  .form-group
    = f.label :name, class: 'col-sm-1 control-label'
    .col-sm-5
      = f.text_field :name, class: 'form-control'
      .help-block{id: 'helpBlock1'} Allowed: one space, letters

  .form-group
    = f.label :name, class: 'col-sm-1 control-label'
    .col-sm-5
    = f.file_field :image, class: 'form-control'

<div class="form-group">
    <%= f.label :gender, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
        <%= f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"}) %>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-1 col-sm-6">
        <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
</div>

<% end %>

app/views/pages/_new_chars.html.erb
<%= form_for @char, html: {class: "form-horizontal"} do |f| %>
<% if @char.errors.any? %>
<div id="errorExplanation">
    <h2><%= pluralize(@char.errors.count, "error") %>
        prohibited this char from being saved:</h2>
    <ul>
        <% @char.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>f
<% end %>

<div class="form-group">
    <%= f.label :name, class: 'col-sm-1 control-label'%>
    <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control' %>
        <span id="helpBlock1" class="help-block">Allowed: one space, letters</span>
    </div>
</div>

<div class="form-group">
    <%= f.label :image, class: 'col-sm-1 control-label'%>
    <div class="col-sm-5">
        <%= f.file_field :image, class: 'form-control' %>
    </div>
</div>

<div class="form-group">
    <%= f.label :gender, class: 'col-sm-1 control-label' %>
    <div class="col-sm-2">
        <%= f.select(:gender, options_for_select([['Male', 1], ['Female', 2]]), {}, {class: "form-control"}) %>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-1 col-sm-6">
        <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
</div>

<% end %>

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.erb
.col-sm-offset-3
  %h2 Edit Character
  %br

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TB-Game", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style='color:white'>Actions<span class="caret"></span></a>

            <ul class="dropdown-menu">

                <li><%= link_to "Petty Crime", petty_crime_path %></li>
                <li role="separator" class="divider"></li>

                <li><%= link_to "Edit Character", edit_char_path %></li>
                <li role="separator" class="divider"></li>

              <li><%= link_to "Edit User", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style='color:white'>User <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <% if !current_user.active_character %>
                <li><%= link_to "Create Character", new_character_path %></li>
                <li role="separator" class="divider"></li>
              <% else %>
                <li><%= link_to "Edit Character", edit_char_path %></li>
                <li role="separator" class="divider"></li>
              <% end %>
              <li><%= link_to "Edit User", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_online.erb
  <br><h6 style>Players online</h6>
<div class="jumbotron" style="text-align:center;padding:0px">

  <p><small>
    <% if Character.online.any? %>
      <% Character.online.sort_by{ |c| c.rank }.reverse.each do |character| %>
        | <%= link_to character.name, character %> |
      <% end %>
    <% else %>
      There are no users online.
    <% end %>
  </small></p>
</div>